### ISSUE TITLE
issue with smplx body model 

### ISSUE THREAD

**Issue by ujjawalcse** [vcarlosrb/3d-body-measurements#1]
Hi 
Thanks for the nice repo and library . 
We tried generating a 3d model with expose https://github.com/vchoutas/expose which tries to fit a smplx body model .
After that we used your library to derive the measurements and here is the error .
Thanks 
`Unimplemented OBJ format statement 'g' on line 'g model'
Unimplemented OBJ format statement 's' on line 's 1'
Traceback (most recent call last):
  File "/home/ujjawal/my_work/Fashion/3d-body-measurements/example/example.py", line 29, in <module>
    main()
  File "/home/ujjawal/my_work/Fashion/3d-body-measurements/example/example.py", line 19, in main
    body = Body3D(vertices, faces)
  File "/home/ujjawal/miniconda2/envs/py3.9/lib/python3.9/site-packages/body_measurements/measurement.py", line 192, in __init__
    _, self.hip_location, _ = getHip(self.sections, self.crotch_location)
  File "/home/ujjawal/miniconda2/envs/py3.9/lib/python3.9/site-packages/body_measurements/measurement.py", line 87, in getHip
    polygon = getLargerAreaPolygon(sections[cont])
TypeError: list indices must be integers or slices, not NoneType
`

**Comment by vcarlosrb** [comment]
Hello,

I think the problem is due to the generated .obj file. I recommend directly using the 'vertices' and 'faces' generated by the model and then using the library using the Body3D class to read the 'vertices' and 'faces'.
Another important point is to **generate the model of the person in pose 'A'**. For SMPL, the elements of the pose vector must be zero except for positions 50 and 53, which must have the values 5.6 and -5.6 respectively. **Since the 'Expose' project uses SMPLX, it would be necessary to investigate what values the elements of the pose vector of said model should have.**

I attach an image using the vertices and faces generated from the 'Expose' project example. The Body3D class can read vertices and faces but cannot calculate body measurements because it is not in pose 'A'
![trimesh](https://user-images.githubusercontent.com/16088635/105625267-d2cdb780-5df5-11eb-8829-5a6f225e62f2.png)

**Comment by ujjawalcse** [comment]
Hey @vcarlosrb , 
Thanks for your kind and helpful information.
Can you provide a reference on how to convert SMPL model to A-pose that is required in this repo?
Thanks .

**Comment by vcarlosrb** [comment]
Hello @ujjawalcse ,

Sure!. I am going to use the https://github.com/gulvarol/smplpytorch layer to generate vertices from the **shape and pose params**. The **shape params is a vector with 10 elements** and the **pose params is a vector too with 72 elements**. To set A pose you can use the two funtions in la row number 14, **the function 'resetPose'** set each element of the pose params with zero, then, **the function 'setAPose'** set the elements of the position 50 and 53 with a random number between 0.5 and 1.3.

I attach an image with the functions described and using Trimesh to render the vertices.
![trimesh](https://user-images.githubusercontent.com/16088635/105798892-30cade00-5f61-11eb-886b-02c502cd594d.png)

**Comment by vcarlosrb** [comment]
@ujjawalcse  If you want examples about the pose and shape params, these files contain many examples of parameters to render meshes of human bodies. 

https://drive.google.com/drive/folders/1CLOqQBrTos7vhohjFcU2OFkNYmyvQf6t

**Comment by AlyanQ** [comment]
Hi @vcarlosrb, is there a way to convert a SMPL model to A pose using the .obj file itself or even recreating it from the .pkl file? I have a pipeline that generates SMPL models but I cannot generate the models in the A pose directly, I need to convert them to the A pose after they have been generated. Much thanks.

**Comment by vcarlosrb** [comment]
Hello AlyanQ,

Ohh, in the your [previous question](https://github.com/vcarlosrb/3d-body-measurements/issues/8#issuecomment-974771408) I commented that is very complex to set A pose only with the .obj file. There are two alternatives, the first one, is set A pose before enter to SMPL model, that is, the required values must be given to the pose parameter. The second one, is find a library or something to generate shape and pose params from .obj file, then modify the pose params that you want, in this case, as requested by the 3d-body-measurements library. I think I came across a library that described the second alternative, [Minimal-IK](https://github.com/CalciferZh/Minimal-IK). I hope I've helped.
