### ISSUE TITLE
Error: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by Adeel-Intizar** [vcarlosrb/3d-body-measurements#8]
I am having this issue while running on a custom obj file
![image](https://user-images.githubusercontent.com/56041154/123735722-28ccec80-d8b9-11eb-958e-f2a547071b7c.png)

**Comment by vcarlosrb** [comment]
Hi @Adeel-Intizar ,

Could you share the vertices and faces to be able to replicate the error and see where it fails?

**Comment by Adeel-Intizar** [comment]
[test.zip](https://github.com/vcarlosrb/3d-body-measurements/files/6788793/test.zip)
This is the OBJ file which generated error

**Comment by vcarlosrb** [comment]
Hi @Adeel-Intizar ,

Sorry for the delay. I see the file you are using does not have the pose that the library needs.
![usado](https://user-images.githubusercontent.com/16088635/125558387-2a6698b5-d6df-467e-a846-ccbf9bcde0ea.png)
The person's pose should be in the shape of an A, like this:
![ideal](https://user-images.githubusercontent.com/16088635/125558409-52f49e18-0553-4c93-863e-500ca6b8e5c9.png)
When you use the SMPL model, it has as input two parameters, shape and pose. The shape parameter is an array of 10 elements, and the pose parameter has 72 elements. What you should do is set all the elements of the pose parameter to 0, except for positions 50 and 53 which should be 5.6 and -5.6 respectively.

![image](https://user-images.githubusercontent.com/16088635/125558984-e9f4a0f8-ab8c-4c7a-be06-b90d4d46b810.png)

**Comment by AlyanQ** [comment]
If I already have a 3D object of a person generated using SMPL model, how would I go about changing the shape parameters to make sure that the pose is in the correct format for accurate measurements? In simple words, is there a way to change a .obj file created using a SMPL model itself or does it need to be changed during creation of the .obj model

**Comment by vcarlosrb** [comment]
Hello AlyanQ,

That's a interesting question. ActuallyI am not sure. While I was manipulating the vertices and faces value of .obj file, when the value of any element of the vertex array changed, even if it was minimal, peaks were generated in the rendered 3D modeling. So, I think, that's very complex to generate a specifict pose or shape using a .obj file. Another reason is because the vertices generated are 63000 elements approximately.

I recommend, setting de pose before enter to the SMPL model, because the pose params have 72 elements, and each element controls a specifict part of the body, therefore, you have more control if you want to get a specifict pose.
